const catalogo = [
  {
    id:"CAT000001",
    nome:"Alma Negra Blend",
    produtor:"Ernesto Catena",
    pais:"Argentina",
    regiao:"Mendoza",
    uva:"Blend",
    tipo:"Tinto",
    temperatura:"16–18°C",
    decantacao:"30 minutos",
    janelaBase:"2025–2032",
    harmonizacao:"Carnes vermelhas, cordeiro, massas e queijos",
    comentario:"Blend elegante, aromático e muito alinhado ao perfil Delucca.",
    nota:5,
    recompra:true,
    naoPodeFaltar:true,
    estoqueMinimo:2,
    corpo:5,
    acidez:3,
    taninos:4,
    fruta:5,
    madeira:3,
    elegancia:5,
    imagem:""
  },
  {
    id:"CAT000002",
    nome:"D.V. Catena Cabernet/Malbec",
    produtor:"Catena Zapata",
    pais:"Argentina",
    regiao:"Mendoza",
    uva:"Cabernet Sauvignon / Malbec",
    tipo:"Tinto",
    temperatura:"16–18°C",
    decantacao:"30 a 45 minutos",
    janelaBase:"2026–2032",
    harmonizacao:"Carnes vermelhas, cordeiro, massas e churrasco premium",
    comentario:"Rótulo essencial, elegante e confiável para ocasiões especiais.",
    nota:5,
    recompra:true,
    naoPodeFaltar:true,
    estoqueMinimo:2,
    corpo:5,
    acidez:4,
    taninos:4,
    fruta:4,
    madeira:4,
    elegancia:5,
    imagem:""
  },
  {
    id:"CAT000003",
    nome:"Catena Alta Malbec",
    produtor:"Catena Zapata",
    pais:"Argentina",
    regiao:"Mendoza",
    uva:"Malbec",
    tipo:"Tinto",
    temperatura:"16–18°C",
    decantacao:"45 a 60 minutos",
    janelaBase:"2027–2038",
    harmonizacao:"Bife ancho, cordeiro, carnes nobres e risoto de cogumelos",
    comentario:"Vinho de guarda, profundo e excelente para momentos especiais.",
    nota:5,
    recompra:true,
    naoPodeFaltar:true,
    estoqueMinimo:2,
    corpo:5,
    acidez:4,
    taninos:5,
    fruta:5,
    madeira:4,
    elegancia:5,
    imagem:""
  },
  {
    id:"CAT000004",
    nome:"Luigi Bosca De Sangre Malbec",
    produtor:"Luigi Bosca",
    pais:"Argentina",
    regiao:"Mendoza",
    uva:"Malbec",
    tipo:"Tinto",
    temperatura:"16–18°C",
    decantacao:"30 a 45 minutos",
    janelaBase:"2026–2033",
    harmonizacao:"Churrasco, carnes vermelhas, massas e queijos curados",
    comentario:"Muito bom, suave e com alta chance de recompra.",
    nota:5,
    recompra:true,
    naoPodeFaltar:true,
    estoqueMinimo:2,
    corpo:4,
    acidez:3,
    taninos:4,
    fruta:5,
    madeira:3,
    elegancia:5,
    imagem:""
  },
  {
    id:"CAT000005",
    nome:"Susana Balbo Signature Malbec",
    produtor:"Susana Balbo",
    pais:"Argentina",
    regiao:"Mendoza",
    uva:"Malbec",
    tipo:"Tinto",
    temperatura:"16–18°C",
    decantacao:"45 minutos",
    janelaBase:"2026–2034",
    harmonizacao:"Carnes vermelhas, cordeiro, massas intensas e queijos",
    comentario:"Rótulo elegante, estruturado e muito alinhado ao perfil Delucca.",
    nota:5,
    recompra:true,
    naoPodeFaltar:true,
    estoqueMinimo:2,
    corpo:5,
    acidez:4,
    taninos:4,
    fruta:5,
    madeira:4,
    elegancia:5,
    imagem:""
  },
  {
    id:"CAT000006",
    nome:"Zuccardi Q Malbec",
    produtor:"Zuccardi",
    pais:"Argentina",
    regiao:"Mendoza",
    uva:"Malbec",
    tipo:"Tinto",
    temperatura:"16–18°C",
    decantacao:"30 minutos",
    janelaBase:"2025–2030",
    harmonizacao:"Carnes grelhadas, massas e pratos condimentados",
    comentario:"Bom vinho, porém mais pesado para o perfil Delucca.",
    nota:3,
    recompra:false,
    naoPodeFaltar:false,
    estoqueMinimo:1,
    corpo:5,
    acidez:4,
    taninos:5,
    fruta:4,
    madeira:4,
    elegancia:3,
    imagem:""
  },
  {
    id:"CAT000007",
    nome:"Latitude 33 Malbec",
    produtor:"Chandon Argentina",
    pais:"Argentina",
    regiao:"Mendoza",
    uva:"Malbec",
    tipo:"Tinto",
    temperatura:"15–17°C",
    decantacao:"15 minutos",
    janelaBase:"2025–2028",
    harmonizacao:"Pizza, massas, carnes simples e churrasco do dia a dia",
    comentario:"Bom custo-benefício para consumo cotidiano.",
    nota:4,
    recompra:true,
    naoPodeFaltar:false,
    estoqueMinimo:2,
    corpo:3,
    acidez:3,
    taninos:3,
    fruta:4,
    madeira:2,
    elegancia:3,
    imagem:""
  },
  {
    id:"CAT000008",
    nome:"Vinha da Valentina Premium",
    produtor:"Vinha da Valentina",
    pais:"Portugal",
    regiao:"Alentejo",
    uva:"Blend",
    tipo:"Tinto",
    temperatura:"16–18°C",
    decantacao:"30 minutos",
    janelaBase:"2025–2030",
    harmonizacao:"Carnes assadas, bacalhau, queijos e pratos mediterrâneos",
    comentario:"Boa opção portuguesa para diversificar a adega.",
    nota:4,
    recompra:true,
    naoPodeFaltar:false,
    estoqueMinimo:1,
    corpo:4,
    acidez:3,
    taninos:3,
    fruta:4,
    madeira:3,
    elegancia:4,
    imagem:""
  },
  {
    id:"CAT000009",
    nome:"Casa Ermelinda Freitas",
    produtor:"Casa Ermelinda Freitas",
    pais:"Portugal",
    regiao:"Península de Setúbal",
    uva:"Blend",
    tipo:"Tinto",
    temperatura:"16–18°C",
    decantacao:"20 minutos",
    janelaBase:"2025–2029",
    harmonizacao:"Carnes assadas, massas, queijos e pratos portugueses",
    comentario:"Rótulo português versátil para consumo casual.",
    nota:4,
    recompra:false,
    naoPodeFaltar:false,
    estoqueMinimo:1,
    corpo:3,
    acidez:3,
    taninos:3,
    fruta:4,
    madeira:2,
    elegancia:3,
    imagem:""
  },
  {
    id:"CAT000010",
    nome:"Felino Malbec",
    produtor:"Viña Cobos",
    pais:"Argentina",
    regiao:"Mendoza",
    uva:"Malbec",
    tipo:"Tinto",
    temperatura:"16–18°C",
    decantacao:"30 minutos",
    janelaBase:"2025–2030",
    harmonizacao:"Carnes vermelhas, hambúrguer artesanal e churrasco",
    comentario:"Malbec moderno, frutado e interessante para comparação.",
    nota:4,
    recompra:true,
    naoPodeFaltar:false,
    estoqueMinimo:1,
    corpo:4,
    acidez:3,
    taninos:4,
    fruta:5,
    madeira:3,
    elegancia:4,
    imagem:""
  },
  {
    id:"CAT000011",
    nome:"Bramare Malbec",
    produtor:"Viña Cobos",
    pais:"Argentina",
    regiao:"Mendoza",
    uva:"Malbec",
    tipo:"Tinto",
    temperatura:"16–18°C",
    decantacao:"45 minutos",
    janelaBase:"2026–2035",
    harmonizacao:"Carnes nobres, cordeiro e pratos intensos",
    comentario:"Malbec de alto nível, excelente para evoluir o paladar.",
    nota:5,
    recompra:true,
    naoPodeFaltar:false,
    estoqueMinimo:1,
    corpo:5,
    acidez:4,
    taninos:5,
    fruta:5,
    madeira:4,
    elegancia:5,
    imagem:""
  },
  {
    id:"CAT000012",
    nome:"Achaval Ferrer Malbec",
    produtor:"Achaval Ferrer",
    pais:"Argentina",
    regiao:"Mendoza",
    uva:"Malbec",
    tipo:"Tinto",
    temperatura:"16–18°C",
    decantacao:"45 minutos",
    janelaBase:"2026–2034",
    harmonizacao:"Carnes vermelhas, cordeiro e queijos curados",
    comentario:"Rótulo argentino elegante para comparar com Catena e Luigi Bosca.",
    nota:5,
    recompra:true,
    naoPodeFaltar:false,
    estoqueMinimo:1,
    corpo:5,
    acidez:4,
    taninos:4,
    fruta:5,
    madeira:3,
    elegancia:5,
    imagem:""
  },
  {
    id:"CAT000013",
    nome:"El Enemigo Cabernet Franc",
    produtor:"El Enemigo",
    pais:"Argentina",
    regiao:"Mendoza",
    uva:"Cabernet Franc",
    tipo:"Tinto",
    temperatura:"16–18°C",
    decantacao:"45 minutos",
    janelaBase:"2026–2035",
    harmonizacao:"Carnes magras, cordeiro, risoto e cogumelos",
    comentario:"Ótimo rótulo para explorar Cabernet Franc argentino.",
    nota:5,
    recompra:true,
    naoPodeFaltar:false,
    estoqueMinimo:1,
    corpo:4,
    acidez:4,
    taninos:4,
    fruta:4,
    madeira:3,
    elegancia:5,
    imagem:""
  },
  {
    id:"CAT000014",
    nome:"Pinto Finale",
    produtor:"Pinto",
    pais:"Argentina",
    regiao:"Mendoza",
    uva:"Cabernet Franc",
    tipo:"Tinto",
    temperatura:"16–18°C",
    decantacao:"20 minutos",
    janelaBase:"2025–2029",
    harmonizacao:"Carnes, massas, hambúrguer e queijos",
    comentario:"Boa opção para comparar com Cabernet Francs superiores.",
    nota:4,
    recompra:false,
    naoPodeFaltar:false,
    estoqueMinimo:1,
    corpo:3,
    acidez:3,
    taninos:3,
    fruta:4,
    madeira:2,
    elegancia:3,
    imagem:""
  },
  {
    id:"CAT000015",
    nome:"Cremaschi Furlotti Gran Reserva Carménère",
    produtor:"Cremaschi Furlotti",
    pais:"Chile",
    regiao:"Valle Central",
    uva:"Carménère",
    tipo:"Tinto",
    temperatura:"16–18°C",
    decantacao:"20 minutos",
    janelaBase:"2025–2029",
    harmonizacao:"Carnes assadas, massas, queijos e pratos levemente condimentados",
    comentario:"Boa opção chilena para diversificar fora do Malbec.",
    nota:4,
    recompra:false,
    naoPodeFaltar:false,
    estoqueMinimo:1,
    corpo:4,
    acidez:3,
    taninos:3,
    fruta:4,
    madeira:3,
    elegancia:4,
    imagem:""
  }
];
