const catalogo = [
  {
    id:"CAT001",
    nome:"Alma Negra Blend",
    produtor:"Alma Negra",
    pais:"Argentina",
    regiao:"Mendoza",
    uva:"Blend",
    temperatura:"16–18°C",
    decantacao:"30 minutos",
    janelaBase:"2025–2032",
    harmonizacao:"Carnes vermelhas, cordeiro, massas e queijos",
    comentario:"Blend elegante, aromático e muito alinhado ao perfil Delucca.",
    nota:5,
    notaDelucca:5,
    recompra:true,
    naoPodeFaltar:true,
    estoqueMinimo:2,
    imagem:""
  },
  {
    id:"CAT002",
    nome:"D.V. Catena Cabernet/Malbec",
    produtor:"Catena Zapata",
    pais:"Argentina",
    regiao:"Mendoza",
    uva:"Cabernet Sauvignon / Malbec",
    temperatura:"16–18°C",
    decantacao:"30 a 45 minutos",
    janelaBase:"2026–2032",
    harmonizacao:"Carnes vermelhas, cordeiro, massas e churrasco premium",
    comentario:"Rótulo essencial, elegante e muito confiável.",
    nota:5,
    notaDelucca:5,
    recompra:true,
    naoPodeFaltar:true,
    estoqueMinimo:2,
    imagem:""
  },
  {
    id:"CAT003",
    nome:"Catena Alta Malbec",
    produtor:"Catena Zapata",
    pais:"Argentina",
    regiao:"Mendoza",
    uva:"Malbec",
    temperatura:"16–18°C",
    decantacao:"45 a 60 minutos",
    janelaBase:"2027–2038",
    harmonizacao:"Bife ancho, cordeiro, carnes nobres e risoto de cogumelos",
    comentario:"Vinho de guarda, profundo e excelente para ocasiões especiais.",
    nota:5,
    notaDelucca:5,
    recompra:true,
    naoPodeFaltar:true,
    estoqueMinimo:2,
    imagem:""
  },
  {
    id:"CAT004",
    nome:"Luigi Bosca De Sangre Malbec",
    produtor:"Luigi Bosca",
    pais:"Argentina",
    regiao:"Mendoza",
    uva:"Malbec",
    temperatura:"16–18°C",
    decantacao:"30 a 45 minutos",
    janelaBase:"2026–2033",
    harmonizacao:"Churrasco, carnes vermelhas, massas e queijos curados",
    comentario:"Muito bom, suave e com alta chance de recompra.",
    nota:5,
    notaDelucca:5,
    recompra:true,
    naoPodeFaltar:true,
    estoqueMinimo:2,
    imagem:""
  },
  {
    id:"CAT005",
    nome:"Susana Balbo Signature Malbec",
    produtor:"Susana Balbo",
    pais:"Argentina",
    regiao:"Mendoza",
    uva:"Malbec",
    temperatura:"16–18°C",
    decantacao:"45 minutos",
    janelaBase:"2026–2034",
    harmonizacao:"Carnes vermelhas, cordeiro, massas intensas e queijos",
    comentario:"Rótulo elegante, estruturado e alinhado ao perfil Delucca.",
    nota:5,
    notaDelucca:5,
    recompra:true,
    naoPodeFaltar:true,
    estoqueMinimo:2,
    imagem:""
  },
  {
    id:"CAT006",
    nome:"Zuccardi Q Malbec",
    produtor:"Zuccardi",
    pais:"Argentina",
    regiao:"Mendoza",
    uva:"Malbec",
    temperatura:"16–18°C",
    decantacao:"30 minutos",
    janelaBase:"2025–2030",
    harmonizacao:"Carnes grelhadas, massas e pratos condimentados",
    comentario:"Bom vinho, porém mais pesado para o perfil Delucca.",
    nota:3,
    notaDelucca:3,
    recompra:false,
    naoPodeFaltar:false,
    estoqueMinimo:1,
    imagem:""
  },
  {
    id:"CAT007",
    nome:"Latitude 33 Malbec",
    produtor:"Chandon Argentina",
    pais:"Argentina",
    regiao:"Mendoza",
    uva:"Malbec",
    temperatura:"15–17°C",
    decantacao:"15 minutos",
    janelaBase:"2025–2028",
    harmonizacao:"Pizza, massas, carnes simples e churrasco do dia a dia",
    comentario:"Bom custo-benefício para consumo cotidiano.",
    nota:4,
    notaDelucca:4,
    recompra:true,
    naoPodeFaltar:false,
    estoqueMinimo:2,
    imagem:""
  },
  {
    id:"CAT008",
    nome:"Vinha da Valentina Premium",
    produtor:"Vinha da Valentina",
    pais:"Portugal",
    regiao:"Alentejo",
    uva:"Blend",
    temperatura:"16–18°C",
    decantacao:"30 minutos",
    janelaBase:"2025–2030",
    harmonizacao:"Carnes assadas, bacalhau, queijos e pratos mediterrâneos",
    comentario:"Boa opção portuguesa para diversificar a adega.",
    nota:4,
    notaDelucca:4,
    recompra:true,
    naoPodeFaltar:false,
    estoqueMinimo:1,
    imagem:""
  }
];
