const catalogo = [
  {
    nome:"Alma Negra Blend",
    produtor:"Alma Negra",
    pais:"Argentina",
    regiao:"Mendoza",
    safra:"2021",
    uva:"Blend",
    janela:"2025–2032",
    harmonizacao:"Carnes vermelhas, cordeiro, massas e queijos",
    comentario:"Blend elegante, aromático e muito alinhado ao perfil Delucca.",
    nota:5,
    notaDelucca:5,
    recompra:true,
    naoPodeFaltar:true,
    estoqueMinimo:2,
    temperatura:"16–18°C",
    decantacao:"30 minutos",
    imagem:""
  },
  {
    nome:"D.V. Catena Cabernet/Malbec",
    produtor:"Catena Zapata",
    pais:"Argentina",
    regiao:"Mendoza",
    safra:"2023",
    uva:"Cabernet Sauvignon / Malbec",
    janela:"2026–2032",
    harmonizacao:"Carnes vermelhas, cordeiro, massas e churrasco premium",
    comentario:"Rótulo essencial, elegante e muito confiável para ocasiões especiais.",
    nota:5,
    notaDelucca:5,
    recompra:true,
    naoPodeFaltar:true,
    estoqueMinimo:2,
    temperatura:"16–18°C",
    decantacao:"30 a 45 minutos",
    imagem:""
  },
  {
    nome:"Catena Alta Malbec",
    produtor:"Catena Zapata",
    pais:"Argentina",
    regiao:"Mendoza",
    safra:"2022",
    uva:"Malbec",
    janela:"2027–2038",
    harmonizacao:"Bife ancho, cordeiro, carnes nobres e risoto de cogumelos",
    comentario:"Vinho de guarda, profundo e excelente para momentos especiais.",
    nota:5,
    notaDelucca:5,
    recompra:true,
    naoPodeFaltar:true,
    estoqueMinimo:2,
    temperatura:"16–18°C",
    decantacao:"45 a 60 minutos",
    imagem:""
  },
  {
    nome:"Luigi Bosca De Sangre Malbec",
    produtor:"Luigi Bosca",
    pais:"Argentina",
    regiao:"Mendoza",
    safra:"2022",
    uva:"Malbec",
    janela:"2026–2033",
    harmonizacao:"Churrasco, carnes vermelhas, massas e queijos curados",
    comentario:"Muito bom, suave e com alta chance de recompra.",
    nota:5,
    notaDelucca:5,
    recompra:true,
    naoPodeFaltar:true,
    estoqueMinimo:2,
    temperatura:"16–18°C",
    decantacao:"30 a 45 minutos",
    imagem:""
  },
  {
    nome:"Luigi Bosca Insignia Malbec",
    produtor:"Luigi Bosca",
    pais:"Argentina",
    regiao:"Mendoza",
    safra:"2024",
    uva:"Malbec",
    janela:"2026–2030",
    harmonizacao:"Churrasco, carnes vermelhas e massas",
    comentario:"Perfil suave, frutado e fácil de agradar.",
    nota:5,
    notaDelucca:5,
    recompra:true,
    naoPodeFaltar:true,
    estoqueMinimo:2,
    temperatura:"16–18°C",
    decantacao:"20 a 30 minutos",
    imagem:""
  },
  {
    nome:"Susana Balbo Signature Malbec",
    produtor:"Susana Balbo",
    pais:"Argentina",
    regiao:"Mendoza",
    safra:"2022",
    uva:"Malbec",
    janela:"2026–2034",
    harmonizacao:"Carnes vermelhas, cordeiro, massas intensas e queijos",
    comentario:"Rótulo elegante, estruturado e muito alinhado ao perfil Delucca.",
    nota:5,
    notaDelucca:5,
    recompra:true,
    naoPodeFaltar:true,
    estoqueMinimo:2,
    temperatura:"16–18°C",
    decantacao:"45 minutos",
    imagem:""
  },
  {
    nome:"Zuccardi Q Malbec",
    produtor:"Zuccardi",
    pais:"Argentina",
    regiao:"Mendoza",
    safra:"2022",
    uva:"Malbec",
    janela:"2025–2030",
    harmonizacao:"Carnes grelhadas, massas e pratos condimentados",
    comentario:"Bom vinho, porém mais pesado para o perfil Delucca.",
    nota:3,
    notaDelucca:3,
    recompra:false,
    naoPodeFaltar:false,
    estoqueMinimo:1,
    temperatura:"16–18°C",
    decantacao:"30 minutos",
    imagem:""
  },
  {
    nome:"Latitude 33 Malbec",
    produtor:"Chandon Argentina",
    pais:"Argentina",
    regiao:"Mendoza",
    safra:"2024",
    uva:"Malbec",
    janela:"2025–2028",
    harmonizacao:"Pizza, massas, carnes simples e churrasco do dia a dia",
    comentario:"Bom custo-benefício para consumo cotidiano.",
    nota:4,
    notaDelucca:4,
    recompra:true,
    naoPodeFaltar:false,
    estoqueMinimo:2,
    temperatura:"15–17°C",
    decantacao:"15 minutos",
    imagem:""
  },
  {
    nome:"Vinha da Valentina Premium",
    produtor:"Vinha da Valentina",
    pais:"Portugal",
    regiao:"Alentejo",
    safra:"2022",
    uva:"Blend",
    janela:"2025–2030",
    harmonizacao:"Carnes assadas, bacalhau, queijos e pratos mediterrâneos",
    comentario:"Boa opção portuguesa para diversificar a adega.",
    nota:4,
    notaDelucca:4,
    recompra:true,
    naoPodeFaltar:false,
    estoqueMinimo:1,
    temperatura:"16–18°C",
    decantacao:"30 minutos",
    imagem:""
  },
  {
    nome:"Vinha da Valentina Premium 2023",
    produtor:"Vinha da Valentina",
    pais:"Portugal",
    regiao:"Alentejo",
    safra:"2023",
    uva:"Blend",
    janela:"2025–2031",
    harmonizacao:"Carnes assadas, massas, bacalhau e queijos",
    comentario:"Safra jovem, boa para acompanhar pratos portugueses.",
    nota:4,
    notaDelucca:4,
    recompra:true,
    naoPodeFaltar:false,
    estoqueMinimo:1,
    temperatura:"16–18°C",
    decantacao:"20 a 30 minutos",
    imagem:""
  },
  {
    nome:"Casa Ermelinda Freitas",
    produtor:"Casa Ermelinda Freitas",
    pais:"Portugal",
    regiao:"Península de Setúbal",
    safra:"2022",
    uva:"Blend",
    janela:"2025–2029",
    harmonizacao:"Carnes assadas, massas, queijos e pratos portugueses",
    comentario:"Rótulo português versátil para consumo casual.",
    nota:4,
    notaDelucca:4,
    recompra:false,
    naoPodeFaltar:false,
    estoqueMinimo:1,
    temperatura:"16–18°C",
    decantacao:"20 minutos",
    imagem:""
  },
  {
    nome:"Felino Malbec",
    produtor:"Viña Cobos",
    pais:"Argentina",
    regiao:"Mendoza",
    safra:"2022",
    uva:"Malbec",
    janela:"2025–2030",
    harmonizacao:"Carnes vermelhas, hambúrguer artesanal e churrasco",
    comentario:"Malbec moderno, frutado e interessante para comparação.",
    nota:4,
    notaDelucca:4,
    recompra:true,
    naoPodeFaltar:false,
    estoqueMinimo:1,
    temperatura:"16–18°C",
    decantacao:"30 minutos",
    imagem:""
  },
  {
    nome:"Bramare Malbec",
    produtor:"Viña Cobos",
    pais:"Argentina",
    regiao:"Mendoza",
    safra:"2021",
    uva:"Malbec",
    janela:"2026–2035",
    harmonizacao:"Carnes nobres, cordeiro e pratos intensos",
    comentario:"Malbec de alto nível, excelente para evoluir o paladar.",
    nota:5,
    notaDelucca:5,
    recompra:true,
    naoPodeFaltar:false,
    estoqueMinimo:1,
    temperatura:"16–18°C",
    decantacao:"45 minutos",
    imagem:""
  },
  {
    nome:"Achaval Ferrer Malbec",
    produtor:"Achaval Ferrer",
    pais:"Argentina",
    regiao:"Mendoza",
    safra:"2021",
    uva:"Malbec",
    janela:"2026–2034",
    harmonizacao:"Carnes vermelhas, cordeiro e queijos curados",
    comentario:"Rótulo argentino elegante para comparar com Catena e Luigi Bosca.",
    nota:5,
    notaDelucca:5,
    recompra:true,
    naoPodeFaltar:false,
    estoqueMinimo:1,
    temperatura:"16–18°C",
    decantacao:"45 minutos",
    imagem:""
  },
  {
    nome:"El Enemigo Malbec",
    produtor:"El Enemigo",
    pais:"Argentina",
    regiao:"Mendoza",
    safra:"2021",
    uva:"Malbec",
    janela:"2026–2033",
    harmonizacao:"Carnes, massas intensas e pratos de inverno",
    comentario:"Excelente rótulo para ampliar a referência de Malbec argentino.",
    nota:5,
    notaDelucca:5,
    recompra:true,
    naoPodeFaltar:false,
    estoqueMinimo:1,
    temperatura:"16–18°C",
    decantacao:"40 minutos",
    imagem:""
  },
  {
    nome:"El Enemigo Cabernet Franc",
    produtor:"El Enemigo",
    pais:"Argentina",
    regiao:"Mendoza",
    safra:"2021",
    uva:"Cabernet Franc",
    janela:"2026–2035",
    harmonizacao:"Carnes magras, cordeiro, risoto e cogumelos",
    comentario:"Ótimo rótulo para começar a explorar Cabernet Franc argentino.",
    nota:5,
    notaDelucca:5,
    recompra:true,
    naoPodeFaltar:false,
    estoqueMinimo:1,
    temperatura:"16–18°C",
    decantacao:"45 minutos",
    imagem:""
  },
  {
    nome:"Pinto Finale",
    produtor:"Pinto",
    pais:"Argentina",
    regiao:"Mendoza",
    safra:"2022",
    uva:"Cabernet Franc",
    janela:"2025–2029",
    harmonizacao:"Carnes, massas, hambúrguer e queijos",
    comentario:"Boa opção para manter na adega e comparar com Cabernet Francs superiores.",
    nota:4,
    notaDelucca:4,
    recompra:false,
    naoPodeFaltar:false,
    estoqueMinimo:1,
    temperatura:"16–18°C",
    decantacao:"20 minutos",
    imagem:""
  },
  {
    nome:"Norton Malbec Reserva",
    produtor:"Bodega Norton",
    pais:"Argentina",
    regiao:"Mendoza",
    safra:"2022",
    uva:"Malbec",
    janela:"2025–2030",
    harmonizacao:"Churrasco, massas e carnes grelhadas",
    comentario:"Malbec clássico e confiável para o dia a dia.",
    nota:4,
    notaDelucca:4,
    recompra:true,
    naoPodeFaltar:false,
    estoqueMinimo:1,
    temperatura:"16–18°C",
    decantacao:"20 minutos",
    imagem:""
  },
  {
    nome:"Salentein Reserve Malbec",
    produtor:"Bodegas Salentein",
    pais:"Argentina",
    regiao:"Valle de Uco",
    safra:"2022",
    uva:"Malbec",
    janela:"2025–2031",
    harmonizacao:"Carnes, cordeiro, massas e queijos",
    comentario:"Boa expressão do Valle de Uco com perfil elegante.",
    nota:4,
    notaDelucca:4,
    recompra:true,
    naoPodeFaltar:false,
    estoqueMinimo:1,
    temperatura:"16–18°C",
    decantacao:"30 minutos",
    imagem:""
  },
  {
    nome:"Cremaschi Furlotti Gran Reserva Carménère",
    produtor:"Cremaschi Furlotti",
    pais:"Chile",
    regiao:"Valle Central",
    safra:"2022",
    uva:"Carménère",
    janela:"2025–2029",
    harmonizacao:"Carnes assadas, massas, queijos e pratos levemente condimentados",
    comentario:"Boa opção chilena para diversificar fora do Malbec.",
    nota:4,
    notaDelucca:4,
    recompra:false,
    naoPodeFaltar:false,
    estoqueMinimo:1,
    temperatura:"16–18°C",
    decantacao:"20 minutos",
    imagem:""
  },
  {
    nome:"Sordo Dolcetto d'Alba",
    produtor:"Giovanni Sordo",
    pais:"Itália",
    regiao:"Piemonte",
    safra:"2022",
    uva:"Dolcetto",
    janela:"2025–2028",
    harmonizacao:"Massas, carnes leves, embutidos e queijos",
    comentario:"Italiano gastronômico para ampliar o repertório fora dos tintos argentinos.",
    nota:4,
    notaDelucca:4,
    recompra:false,
    naoPodeFaltar:false,
    estoqueMinimo:1,
    temperatura:"14–16°C",
    decantacao:"15 minutos",
    imagem:""
  },
  {
    nome:"Santa Maria dei Servi",
    produtor:"Santa Maria dei Servi",
    pais:"Itália",
    regiao:"Itália",
    safra:"2022",
    uva:"Tinto seco",
    janela:"2025–2027",
    harmonizacao:"Massas simples, pizza e queijos leves",
    comentario:"Rótulo que não agradou tanto ao perfil Delucca.",
    nota:2,
    notaDelucca:2,
    recompra:false,
    naoPodeFaltar:false,
    estoqueMinimo:0,
    temperatura:"14–16°C",
    decantacao:"10 minutos",
    imagem:""
  }
];
